POST https://auth-book.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "shohrukh",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

###

POST https://auth-book.herokuapp.com/api/users/0
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "Ali",
  "password": "pass"
}

###

POST https://auth-book.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "Ali",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET http://localhost:9999/api/products
Authorization: Bearer {{auth_token}}

###

POST http://localhost:9999/api/products/0
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "The great Getsby",
  "description": "about history",
  "price": 5,
  "pic": "848"
}

###

DELETE http://localhost:9999/api/products/2
Authorization: Bearer {{auth_token}}

###

